### ISSUE TITLE
AttributeError while training Random Search from scratch.

### ISSUE THREAD

**Issue by JiaojiaoYe1994** [zhengxiawu/rethinking_performance_estimation_in_NAS#10]
When I try to train these random architectures from scratch, I got the following error. Do you use Dataset with special structure? 

```
python augment.py --name=RS_BPE1 --file=random_darts_architecture.txt --data_path=data/ --save_path=experiment/ --batch_size=128 --lr=0.03 --layers=6 --init_channels=8 --epochs=10 --cutout_length=0 --image_size=16
Using multi genotypes from file
Genotype(normal=[[('avg_pool_3x3', 1), ('sep_conv_5x5', 0)], [('avg_pool_3x3', 0), ('dil_conv_5x5', 2)], [('dil_conv_5x5', 0), ('dil_conv_5x5', 1)], [('avg_pool_3x3', 1), ('max_pool_3x3', 4)]], normal_concat=range(2, 6), reduce=[[('dil_conv_3x3', 1), ('skip_connect', 0)], [('dil_conv_3x3', 2), ('sep_conv_3x3', 1)], [('sep_conv_5x5', 1), ('max_pool_3x3', 2)], [('skip_connect', 4), ('dil_conv_3x3', 3)]], reduce_concat=range(2, 6))

08/28 12:32:02 PM | 
08/28 12:32:02 PM | Parameters:
08/28 12:32:02 PM | AUX_WEIGHT=0.4
08/28 12:32:02 PM | BATCH_SIZE=128
08/28 12:32:02 PM | CUTOUT_LENGTH=0
08/28 12:32:02 PM | DATA_LOADER_TYPE=Torch
08/28 12:32:02 PM | DATA_PATH=data/
08/28 12:32:02 PM | DATASET=CIFAR10
08/28 12:32:02 PM | DROP_PATH_PROB=0.2
08/28 12:32:02 PM | EPOCHS=10
08/28 12:32:02 PM | FILE=random_darts_architecture.txt
08/28 12:32:02 PM | FP16=False
08/28 12:32:02 PM | GENOTYPE=Genotype(normal=[[('avg_pool_3x3', 1), ('sep_conv_5x5', 0)], [('avg_pool_3x3', 0), ('dil_conv_5x5', 2)], [('dil_conv_5x5', 0), ('dil_conv_5x5', 1)], [('avg_pool_3x3', 1), ('max_pool_3x3', 4)]], normal_concat=range(2, 6), reduce=[[('dil_conv_3x3', 1), ('skip_connect', 0)], [('dil_conv_3x3', 2), ('sep_conv_3x3', 1)], [('sep_conv_5x5', 1), ('max_pool_3x3', 2)], [('skip_connect', 4), ('dil_conv_3x3', 3)]], reduce_concat=range(2, 6))

08/28 12:32:02 PM | GPUS=[0]
08/28 12:32:02 PM | GRAD_CLIP=5.0
08/28 12:32:02 PM | I=0
08/28 12:32:02 PM | IMAGE_SIZE=16
08/28 12:32:02 PM | INIT_CHANNELS=8
08/28 12:32:02 PM | LAYERS=6
08/28 12:32:02 PM | LR=0.03
08/28 12:32:02 PM | MOMENTUM=0.9
08/28 12:32:02 PM | NAME=RS_BPE1
08/28 12:32:02 PM | PATH=experiment/RS_BPE1/3
08/28 12:32:02 PM | PRINT_FREQ=200
08/28 12:32:02 PM | SAVE_DIR=experiment/
08/28 12:32:02 PM | SAVE_PATH=experiment/
08/28 12:32:02 PM | SEED=2
08/28 12:32:02 PM | WEIGHT_DECAY=0.0003
08/28 12:32:02 PM | WORKERS=4
08/28 12:32:02 PM | 
08/28 12:32:02 PM | Logger is set - training start
08/28 12:32:02 PM | Torch version is: 1.6.0+cu101
08/28 12:32:02 PM | Torch_vision version is: 0.7.0+cu101
Files already downloaded and verified
Traceback (most recent call last):
  File "augment.py", line 246, in <module>
    main()
  File "augment.py", line 43, in main
    config.dataset, config.data_path, config.image_size, config.cutout_length, validation=True)
  File "/home/zjlab/yejiaojiao/test/rethinking_performance_estimation_in_NAS/utils.py", line 31, in get_data
    shape = trn_data.train_data.shape
AttributeError: 'CIFAR10' object has no attribute 'train_data'
```

**Comment by zhengxiawu** [comment]
The problem is caused by different torchvision versions. There are two solutions:
1. downgrading your torchvision
2.change  File "/home/zjlab/yejiaojiao/test/rethinking_performance_estimation_in_NAS/utils.py", line 31 from shape = trn_data.train_data.shape to shape = trn_data.data.shape
